version: "3.7"
# this file setup various thinks that are for dev environment

services:
  es01:
    ports:
      - "${ES_PORT}:9200"
  searchservice:
    build:
      context: .
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    volumes:
      # mount code dynamically
      - "./app:/code/app"
