version: "3.7"
# this file setup various thinks that are for dev environment

x-searchservice-base: &searchservice-base
  build:
    context: .
    args:
      USER_UID: ${USER_UID:-1000}
      USER_GID: ${USER_GID:-1000}
  volumes:
    # mount code dynamically
    - "./app:/code/app"


services:
  es01:
    ports:
      - "${ES_PORT}:9200"
  searchservice:
    <<: *searchservice-base
    # uvicorn in reload mode
    command: ["uvicorn", "app.api:app", "--proxy-headers", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  searchupdate:
    <<: *searchservice-base
